title: iLibrary App
description: Manage IBM i tasks with speed and efficiency. Bridge the gap between green screen and desktop.
remote_theme: pages-themes/cayman@v0.2.0

url: "https://www.ilibrary.app"
baseurl: ""

include: [src]