name: Build and Upload EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Hilft, die Installation beim nächsten Mal zu beschleunigen

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller flet # Falls dein Skript flet nutzt, hier mit installieren
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build EXE

        env:
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "utf-8"
        run: echo "y" | python build_tool.py windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: build/windows/